### ISSUE TITLE
ET-Mariphilia-v0.2.1b问题反馈

### ISSUE THREAD

**Issue by bitterly369** [ET-Team/ET-Mariphilia-Public#10]
描述BUG
1.热力实验室结构错误，余烬能量输入仓被你给改没了
2.铁工具依旧没有合成配方

如何重现

原本期望
1.用chisel中的实验室方块代替多方块结构中的石头
2.增加高级滤网的合成配方
3.钻石没有需要用到它合成的配方
4.inspirations红石火把拉杆和红石桶没有合成配方
5.各种古代砖块没有对应的合成配方，用作装饰或者模块化机器还是很好看的
6.灰烬套装没有合成方式

结论：这个版本不能玩

**Comment by dong031001** [comment]
非BUG：
铁工具
红石拉杆及桶
滤网
钻石
Chisel在基础材料学解锁，无法构建结构
