### ISSUE TITLE
[其他]水下建筑巨麻烦望增加更高级的建筑之杖合成

### ISSUE THREAD

**Issue by Death-123** [ET-Team/ET-Mariphilia-Public#12]
水下建筑非常之麻烦,而铁等级的建筑之杖不能覆盖流体,强化建筑指导仪也无法覆盖流体,而水肺药水所需河豚也无法获得,导致水下建筑麻烦无比.
希望加入更高级建筑之杖的合成,或加入海绵或海绵棒的合成

**Comment by dong031001** [comment]
若能获得水肺药水是否可以替代高级建筑之杖？

**Comment by Death-123** [comment]
水肺药水能减去换气的时间,可以让水下建筑方便一些,是一个解决办法
但若可以,还是希望是能添加建筑之杖的合成表,即使比较昂贵.
