### ISSUE TITLE
[BUG]箱子无法打开

### ISSUE THREAD

**Issue by ghost** [ET-Team/ET-Mariphilia-Public#14]
**描述BUG**
箱子无法打开，（个人安装了optifine，并使用了光影，虽然感觉不是这个原因）
**如何重现**
尝试 打开箱子
**原本期望**
若无此BUG，原本你期待发生什么？

**截图**
图片莫名上传不了
简单地说就是右键尝试打开箱子，右上角浮现发现未知错误的提示框，ctrl加i打开后，说将错误文档放置在下面的report中

**运行环境（请越详细越好）:**
 - 操作系统*：Win10
 - 运行内存：16G，分配给mc的为8G
 - Java版本：JAVA8
- 整合包版本*：0,2,2B

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件
[crash-2020-02-14_15.55.12-server.txt](https://github.com/ET-Team/ET-Mariphilia-Public/files/4203355/crash-2020-02-14_15.55.12-server.txt)

**Comment by dong031001** [comment]
无法复现。重启游戏后问题依然出现吗？

**Comment by ghost** [comment]
> 无法复现。重启游戏后问题依然出现吗？

重启游戏后依然出现，或许我可以重新下载一次整合包然后将存档转移过去？

**Comment by ghost** [comment]
我尝试了一下 重新安装了整合包  正常了 可能是下载的哪里出了问题 c
