### ISSUE TITLE
[BUG]一些错误和建议集合反馈

### ISSUE THREAD

**Issue by bitterly369** [ET-Team/ET-Mariphilia-Public#2]
**描述BUG**
1.楼梯不能做
2.半砖不能做
3.铁剑刃只能做模具，不能做铁剑，别的铁零件也一样
4.相同的工具不能通过简单的合并来增加耐久
5.热力实验室多方块结构有问题，缺一个方块
6.一个炼狱锻造炉的配方用两个炼狱锻造炉来制作（我做我自己）
7.bdsandm:upgrade的升级容量x64在基础物流学阶段解锁，却在基础物流学阶段做不了

**如何重现**

**原本期望**
1.可以给个提示告诉玩家利用ftbu实现防爆功能
2.只有把第一阶段的所有任务都完成第二阶段才会解锁（这个不算bug，但是需要提示玩家）
3.热力实验室的操作太蛋疼了，把射线枪放进去，拿出来，再放进去，再拿出来……重重复复重重复复（这个不算bug，但我就是想吐槽）
4.灰烬金属板的材质跟其他金属板不一样（这个不算bug，就是看着别扭）
5.靠剪树叶获得的植物线太少了，不划算（这个不算bug，只是有些不平衡）
6.你为啥不用chisel的实验室方块代替多方块结构中的石头，那个比石头好看（这个不算bug，但我就是想吐槽）
7.没有bibliocraft的写字板记个炼金配方都困难

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：
- 整合包版本*：

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
2020.1.28日
修复6，7
