### ISSUE TITLE
[BUG]研究台空白

### ISSUE THREAD

**Issue by 360735mod12** [ET-Team/ET-Mariphilia-Public#20]
**描述BUG**

**如何重现**

**原本期望**
若无此BUG，原本你期待发生什么？

**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：
- 整合包版本*：

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
模板内容全部空白，你想让我怎么处理？你上医院跟大夫说我疼，大夫只能跟你说忌辛辣。
