### ISSUE TITLE
[BUG]v0.3.0b的一些Bug汇总

### ISSUE THREAD

**Issue by shangjun123** [ET-Team/ET-Mariphilia-Public#21]
**描述BUG**
1.中型灰烬能量输入仓 需要 小型灰烬能量输出仓 合成。
2.基础电学后面的研究都研究不了。
3.医药实验室需要铁门，而铁门无法合成。
4.基础通用线缆的任务检测不到。

**如何重现**
不知道

**原本期望**
做mek机器

**截图**
无

**运行环境（请越详细越好）:**
 - 操作系统*：Windows 10
 - 运行内存：8G
 - Java版本：Java 8 Update 241
- 整合包版本：v0.3.0b

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by tuna5544** [comment]
基础电学后面的研究需要使用智慧透支药物才能解锁

**Comment by shangjun123** [comment]
可是铁门做不了，就导致做不了智慧透支药

**Comment by tuna5544** [comment]
> 可是铁门做不了，就导致做不了智慧透支药
所列的bug新版本均已修复。
你可以先在jei中拿一个铁门来进行游戏，之后等待版本更新。

**Comment by tuna5544** [comment]
> 可是铁门做不了，就导致做不了智慧透支药

所列的bug新版本均已修复.
你可以先在JEI中拿一个铁门来进行游戏，之后等待版本更新.
