### ISSUE TITLE
[BUG]Bug & 建议

### ISSUE THREAD

**Issue by shangjun123** [ET-Team/ET-Mariphilia-Public#22]
**描述BUG**
灰烬能量涡轮机摆不了灰烬能量输入仓，导致整个游戏进度无法前进。

**建议**
还有，生物聚合材料板过于昂贵，而且4个板才出1个锇，而mek对锇的需求量是巨大的，建议改便宜一点。

**运行环境（请越详细越好）:**
 - 操作系统*：Windows 10
 - 运行内存：10G
 - Java版本：Java 8 Update 241
- 整合包版本：v0.3.0b

**Comment by shangjun123** [comment]
还有，建议增加一个快速获得岩浆的合成

**Comment by shangjun123** [comment]
灰烬能量涡轮机是说，有三个位置，可以随便摆，但是摆余烬能量输入仓摆了就不行

**Comment by dong031001** [comment]
收到，将会在下个快照版本修复。
