### ISSUE TITLE
[BUG]个人游玩遇到的bug和建议

### ISSUE THREAD

**Issue by dozbamb** [ET-Team/ET-Mariphilia-Public#3]
**描述BUG**
1.古代宝典每次重进进度丢失，需要重新点一遍
2.地狱门可用浇筑，进入地狱可直接获取部分资源（不知道算不算bug）
3.植物催熟后可用右键一直收获
4.压力计无合成表，无法制作
5.晶胞灰烬能量单元中高级灰烬能量电容无材质无配方
6.无法获取青金石，导致部分物品无法制作
7.花无法合成染料，甜菜南瓜种子无法制作，动物学无法解锁
8.干草块无合成表，生命炼成祭坛无法制作
9.基础信号学中，大气能量测量表无合成表，智械机关合成表中包含进阶信号学的物品
10.升级：容量X64无配方导致一系列升级无法完成
11.基础信号学中智械机关合成表中有进阶信号学的太古电路，同时太古电路无合成表。
12.进阶物流学中机械泵无合成表
13.基础怪物学：滑滑石需要浮冰经铁砧砸成冰，但没有精准的工具采集
14.进阶材料学无法解锁，高阶练金学知识有合成表能使用并解锁阶段二（应该不是bug，只是没做完）

**个人意见**
1.生活调味料在前期造成了极大困扰，食物太少，而生物学阶段制作出治愈方块就再也不用吃东西了（不算bug，个人意见）
2.原版合成表删除过多，需要再适当添加
3.任务描述及奖励有待后续版本添加（很多物品我都不会用，不过测试阶段可以理解）
4.可以考虑添加embers的jei附属，虽然后期有相应的表可用（这个纯属个人意见，仅供参考）

**运行环境（请越详细越好）:**
 - 操作系统*：
 - 运行内存：
 - Java版本：
- 整合包版本*：0.2.0b

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
感谢反馈!顺便一提，不是原版合成表删太多了...是全部都删完了，所有的配方都是我们手写的。

**Comment by dong031001** [comment]
以及，在钓鱼获得的箱子中可以获得青金石，我会考虑添加一个复制配方的。

**Comment by dong031001** [comment]
2020.1.28
修复BUG:
2,4,5,6,7,8,9,10,11,12,14
剩余：
植物催熟
冰获取方式

**Comment by dong031001** [comment]
2020.2.5
全部修复
