### ISSUE TITLE
游戏中灰烬炉下面那个存电的设备没点了，我现在烧不了灰了，直接没法玩了

### ISSUE THREAD

**Issue by ISusu** [ET-Team/ET-Mariphilia-Public#38]
游戏中灰烬炉下面那个存电的设备没点了，我现在烧不了灰了，直接没法玩了

本来好好的，我正烧灰，我关闭拉杆，停止了供电，然后当炉子烧不动的时候我再打开拉杆供电，发现没反应了，不供电了，直接GG了，我现在刚把7个红砖做出来。

![Uploading 2020-08-18_22.16.36.png…]()
![2020-08-18_22 16 52](https://user-images.githubusercontent.com/11419237/90524411-9b9d0f80-e1a0-11ea-8132-7a0f2c6104e5.png)

**Comment by dong031001** [comment]
GG
