### ISSUE TITLE
[BUG]双人联机，客机无法使用研究台研究

### ISSUE THREAD

**Issue by 1103493191** [ET-Team/ET-Mariphilia-Public#48]
**描述BUG**
已经研究完生物学和基础信号学，之后突然不可以研究（显示界面在研究灰烬学界面，点击研究无效）。之前还遇到过一次，是客机研究完灰烬学后无法研究其他学科。
**如何重现**
未知QAQ
**原本期望**
提供一种解决办法：盗版的话，修改登录ID再登录，使用新研究台即可继续进行。

**截图**
无
**运行环境（请越详细越好）:**双人联机，均安装自定局域网联机
 - 操作系统*：win10
 - 运行内存：自动分配，目前5G
 - Java版本：pcl2自动选择
- 整合包版本*：最新版1.0.5

**Comment by dong031001** [comment]
尝试过更换服务端联机吗

**Comment by 1103493191** [comment]
没有尝试过，因为我回家网络很差，会导致联机很卡……

**Comment by dong031001** [comment]
@Snownee

**Comment by Snownee** [comment]
https://github.com/Snownee/Kiwi/issues/30 可能是这个问题吧
