### ISSUE TITLE
[集合]BUG和建议

### ISSUE THREAD

**Issue by 330377782** [ET-Team/ET-Mariphilia-Public#6]
BUG
1.太古电路没有合成表
2.大气能量测试表没有合成表
3.晶胞灰烬能量单元中高级灰烬能量电容没有合成表
4.压力计没有合成表
5.机械泵没有合成表
6.容量X64没有合成表
7.干草块没有合成表
8.小型物品输入仓没有合成表
9.生命炼成祭坛结构有问题，干草块为16个任务是15个

建议
1.深海压力测试站加入工作地区提示
2.建议用阶段来解锁任务
3.建议增加机械蓝图合成表

疑问
1.黑曜石的采集方法
2.钓上来的鱼有啥用

版本：0.2.0b

**Comment by jimmykr** [comment]
黑曜石不是可以用发条稿采集吗，鱼不是用剑可以切片吗。。。。。。

**Comment by 330377782** [comment]
> 黑曜石不是可以用发条稿采集吗，鱼不是用剑可以切片吗。。。。。。

谢谢

**Comment by 330377782** [comment]
BUG
1.太古电路没有合成表
2.大气能量测试表没有合成表
3.晶胞灰烬能量单元中高级灰烬能量电容没有合成表
4.压力计没有合成表
5.机械泵没有合成表
6.容量X64没有合成表

建议
1.深海压力测试站加入工作地区提示
2.建议用阶段来解锁任务
3.建议增加机械蓝图合成表

疑问
1.黎明石砧合成不了锄头

版本：0.2.0b

**Comment by dozbamb** [comment]
压力计进一步的合成表上有y轴范围
