### ISSUE TITLE
[BUG] 关于0.2.1b 版本的错误

### ISSUE THREAD

**Issue by Skrtono** [ET-Team/ET-Mariphilia-Public#8]
**描述BUG**
1、烧复燃灰的时候一次性丢灰烬 可能会导致灰烬不消耗。
2、在服务器中 拿取板条箱物品时 背包如果是满的 会退出服务器。
3、压力计的黑色染色玻璃无法合成。
4、因为加了水产养殖，无法钓到合成豹猫蛋需要的生鱼。
5、热力实验室结构有问题 第三层
**如何重现**

**原本期望**
若无此BUG，原本你期待发生什么？
希望加了原版门的合成配方。
**截图**

**运行环境（请越详细越好）:**
 - 操作系统*：Windows 10 1909 64位
 - 运行内存：2048MB
 - Java版本：java8_241
- 整合包版本*：0.2.1b

**错误报告**
若游戏崩溃，请附上游戏根目录下crash-report文件夹内最新的文件

**Comment by dong031001** [comment]
4.可以潜水杀鱼获得生鱼
